version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8123:8000"
    environment:
      - DB_URI=postgresql://postgres:postgres@db:5432/webhook_trader
      - DB_ECHO=true
    depends_on:
      - db
    networks:
      - webhook-network

  db:
    image: postgres:16-alpine
    ports:
      - "5555:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=webhook_trader
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - webhook-network

  pgadmin:
    image: dpage/pgadmin4:latest
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./pgadmin-servers.json:/pgadmin4/servers.json
    depends_on:
      - db
    networks:
      - webhook-network

volumes:
  postgres_data:
  pgadmin_data:

networks:
  webhook-network:
    driver: bridge 
