# fly.toml app configuration file generated for webhook-trader on 2025-06-02T11:57:43-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'webhook-trader'
primary_region = 'ewr'

[build]

[[mounts]]
  source = 'webhook_trader_data'
  destination = '/data'
  initial_size = '1gb'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
